{{- range $name, $config := .Values.g2krepeaters }}
{{- if and $config.enabled (($config.podDisruptionBudget).enabled | default false) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: g2krepeater-{{ $name }}
  labels:
    app: g2krepeater
    instance: {{ $name }}
spec:
  {{- include "g2k.podDisruptionBudget.availability" $config.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app: g2krepeater
      instance: {{ $name }}
{{- end }}
{{- end }}
