{{- range $name, $config := .Values.g2krepeaters }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: g2krepeater-{{ $name }}
  labels:
    app: g2krepeater
    instance: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: g2krepeater
    instance: {{ $name }}
{{- end }}
{{- end }}
